# Chirp Configuration File
# This file can be placed in:
# 1. /usr/local/etc/chirp.toml (system-wide)
# 2. ~/.config/chirp/chirp.toml (user-specific)
# 3. ./chirp.toml (local directory)
# Later files override settings from earlier ones.

# Shell to use (defaults to $SHELL environment variable)
shell = ""  # Empty means use $SHELL or fallback to /bin/sh

# Input sound configuration (when you type)
[input_sound]
frequency = 587.33  # Note D5
duration_ms = 25    # Duration in milliseconds
volume = 0.35      # Volume level (0.0 to 1.0)

# Output sound configuration (terminal output)
[output_sound]
frequency = 392.00  # Note G4
duration_ms = 35    # Duration in milliseconds
volume = 0.25      # Volume level (0.0 to 1.0)

# Advanced settings
echo_timeout_ms = 1    # Time to wait before considering output not an echo
min_sound_gap_ms = 25  # Minimum time between sounds
debug = false          # Enable debug logging
