# Sample chirp configuration file

[samples]
  # Local feedback for typing
  [samples.local]
    frequency = 392  # G4 note
    duration = 40    # milliseconds
    volume = 0.3     # 0.0 to 1.0

  # Remote feedback for shell output
  [samples.remote]
    frequency = 587  # D5 note
    duration = 300
    volume = 0.3

  # Special feedback for errors
  [samples.error]
    frequency = 220  # A3 note
    duration = 100
    volume = 0.4

[queues]
  # Match enter key and common line endings
  [queues.local]
    match = ["\n"]
    sample = "local"
    max_length = 1

  # Match common shell prompt characters
  [queues.remote]
    match = ["$", "#", "%", ">"]
    sample = "remote"
    max_length = 1

  # Match common error indicators
  [queues.error]
    match = ["error:", "Error:", "ERROR:", "failed:", "Failed:", "FAILED:", "loss"]
    sample = "error"
    max_length = 2  # Allow a small queue for rapid errors
